/**
 * Source file for the cpp_producer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "cpp_producer.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace ModelEn { namespace cpp_producer { 

cpp_producer::cpp_producer(int &In_En) :
    CodeBlock(), In_En(In_En){
  SETNAME(this, "cpp_producer");

  // protected region constructor on begin
  // protected region constructor end
}

cpp_producer::~cpp_producer()
{
  // protected region destructor on begin
  // protected region destructor end
}

void cpp_producer::execute()
{
  // protected region execute code on begin
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
