/**
 * Source file for the ModelEn model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "ModelEn.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace ModelEn { 

ModelEn::ModelEn(ChannelOut<int> *pt_out, ChannelIn<LUNA::Clock::period_t> *pt_timer) :
    Sequential(NULL)
{
  SETNAME(this, "ModelEn");

  // Initialize model objects
  mycpp_encoder = new cpp_encoder::cpp_encoder(encoder);
  SETNAME(mycpp_encoder, "cpp_encoder");
  myreader_encoder = new Reader<int>(&encoder, pt_out);
  SETNAME(myreader_encoder, "reader_encoder");
  mywr_timer = new Writer<LUNA::Clock::period_t>(&timeDummy, pt_timer);
  SETNAME(mywr_timer, "wr_timer");

  // Create SEQUENTIAL group
  mySEQUENTIAL = new Sequential(
    (CSPConstruct *) myreader_encoder,
    (CSPConstruct *) mycpp_encoder,
    NULL
  );
  SETNAME(mySEQUENTIAL, "SEQUENTIAL");


  // Register model objects
  this->append_child(mywr_timer);
  this->append_child(mySEQUENTIAL);

  // protected region constructor on begin
  // protected region constructor end
}

ModelEn::~ModelEn()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete mySEQUENTIAL;

  // Destroy model objects
  delete mywr_timer;
  delete myreader_encoder;
  delete mycpp_encoder;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
