# build.mk file for encoderArch.archm, provide information to 'project MakeFile' 
# Generated by the TERRA Arch2LUNA generator version 1.0.1
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/encoderArch

encoderArch/encoderArch:
	@echo
	@echo "Building $@"
	@make -C encoderArch --no-print-directory

bin/encoderArch: encoderArch/encoderArch | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/encoderArch gets properly rebuild
encoderArch/encoderArch: encoderArch/src/main.cpp ModelEn/lib/libModelEn.a
encoderArch/encoderArch: encoderArch/src/MainModel.cpp encoderArch/include/MainModel.h ModelEn/include/ModelEn/ModelEn.h

# protected region additional dependencies on begin
# protected region additional dependencies end