# build.mk file for timer3.archm, provide information to 'project MakeFile' 
# Generated by the TERRA Arch2LUNA generator version 1.0.1
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/timer3

timer3/timer3:
	@echo
	@echo "Building $@"
	@make -C timer3 --no-print-directory

bin/timer3: timer3/timer3 | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/timer3 gets properly rebuild
timer3/timer3: timer3/src/main.cpp ModelTimer/lib/libModelTimer.a
timer3/timer3: timer3/src/MainModel.cpp timer3/include/MainModel.h ModelTimer/include/ModelTimer/ModelTimer.h

# protected region additional dependencies on begin
# protected region additional dependencies end