/**
 * Header file for the XXControllerTiltModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * 20-sim C++ glue code to connect to ControllerTiltModel
 * Modifying this file is absolutely not recommended!
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
#include "xxsim/ControllerTiltModel.hpp" 
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace ControllerTilt { namespace XXControllerTiltModel { 

class XXControllerTiltModel : public CodeBlock
{

public:
  // Define constructor and destructor
  XXControllerTiltModel(double &SetPointTilt, double &measIO, double &steerIO);
  virtual ~XXControllerTiltModel();

  void execute();

private:

  // Class variables
  double &SetPointTilt;
  double &measIO;
  double &steerIO;

  ControllerTiltModel *m_model;
};

// Close namespace(s)
} } 
