/**
 * Source file for the CPP_pr model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer/CPP_pr.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Producer { namespace CPP_pr { 

CPP_pr::CPP_pr(int &var) :
    CodeBlock(), var(var){
  SETNAME(this, "CPP_pr");

  // protected region constructor on begin
  // protected region constructor end
}

CPP_pr::~CPP_pr()
{
  // protected region destructor on begin
  // protected region destructor end
}

void CPP_pr::execute()
{
  static int numbers = 3;
  static int values [3];
  if(numbers==3)
  {
	  printf("Insert 3 numbers: \n");
	  for(int i=0;i<numbers;i++)
	  {
		  scanf("%d",&values[i]);
		  if(i==numbers-1)
			  numbers=0;
	  }
  }

  var = values[numbers];
  printf("sending %d \n",var);
  numbers++;
  // protected region execute code on begin
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
