# build.mk file for JoyStick.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libJoyStick.a

JoyStick/lib/libJoyStick.a:
	@echo
	@echo "Building $@"
	@make -C JoyStick --no-print-directory

lib/libJoyStick.a: JoyStick/lib/libJoyStick.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libJoyStick.a gets properly rebuild
JoyStick/lib/libJoyStick.a: JoyStick/src/JoyStick.cpp JoyStick/include/JoyStick/JoyStick.h
JoyStick/lib/libJoyStick.a: JoyStick/src/FMI_JoyStick.cpp JoyStick/include/JoyStick/FMI_JoyStick.h JoyStick/include/JoyStick/fmi2Functions.h JoyStick/include/JoyStick/logger.h

# protected region additional dependencies on begin
# protected region additional dependencies end