/**
 * Source file for the EncoderHorizontal model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "EncoderHorizontal.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace EncoderHorizontal { 

EncoderHorizontal::EncoderHorizontal(ChannelOut<int> *encoder_pt, ChannelIn<double> *pt_encoderH_out) :
    Sequential(NULL)
{
  SETNAME(this, "EncoderHorizontal");

  // Initialize model objects
  myencoder_cpp = new encoder_cpp::encoder_cpp(in, out);
  SETNAME(myencoder_cpp, "encoder_cpp");
  myreader_encoder_h = new Reader<int>(&in, encoder_pt);
  SETNAME(myreader_encoder_h, "reader_encoder_h");
  mywriter_encoder_h = new Writer<double>(&out, pt_encoderH_out);
  SETNAME(mywriter_encoder_h, "writer_encoder_h");


  // Register model objects
  this->append_child(myreader_encoder_h);
  this->append_child(myencoder_cpp);
  this->append_child(mywriter_encoder_h);

  // protected region constructor on begin

  // protected region constructor end
}

EncoderHorizontal::~EncoderHorizontal()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin

  // protected region destructor end

  // Destroy model objects
  delete mywriter_encoder_h;
  delete myreader_encoder_h;
  delete myencoder_cpp;
}



// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} 
