/**
 * Source file for the encoder_cpp model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "encoder_cpp.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace EncoderHorizontal { namespace encoder_cpp { 

encoder_cpp::encoder_cpp(int &input, double &output) :
    CodeBlock(), input(input), output(output){
  SETNAME(this, "encoder_cpp");

  // protected region constructor on begin

  // protected region constructor end
}

encoder_cpp::~encoder_cpp()
{
  // protected region destructor on begin

  // protected region destructor end
}

void encoder_cpp::execute()
{
  // protected region execute code on begin
   this->output = (int32_t) input;
  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
