/**
 * Source file for the cpp_horizontal_check model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Check/cpp_horizontal_check.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace JIWY { namespace Check { namespace cpp_horizontal_check { 

cpp_horizontal_check::cpp_horizontal_check(double &horizontal) :
    CodeBlock(), horizontal(horizontal){
  SETNAME(this, "cpp_horizontal_check");

  // protected region constructor on begin
  // protected region constructor end
}

cpp_horizontal_check::~cpp_horizontal_check()
{
  // protected region destructor on begin
  // protected region destructor end
}

void cpp_horizontal_check::execute()
{
  // protected region execute code on begin
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
