/**
 * Header file for the ControllerTilt model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "FMI_ControllerTilt.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace ControllerTilt { 

class ControllerTilt : public Sequential
{

public:
  // Define constructor and destructor
  ControllerTilt(ChannelOut<double> *SetPointTilt, ChannelOut<double> *measIO, ChannelIn<double> *steerIO);
  virtual ~ControllerTilt();

private:

  // Class variables
  double v_SetPointTilt;
  double v_measIO;
  double v_steerIO;

  // Model objects
  FMI_ControllerTilt::FMI_ControllerTilt *myFMI_ControllerTilt;
  Reader<double> *myr_SetPointTilt;
  Reader<double> *myr_measIO;
  Writer<double> *myw_steerIO;

  // Model groups
  Parallel *myIO;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
