# build.mk file for EncoderHorizontal.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin

# protected region document description end

TARGETS+=lib/libEncoderHorizontal.a

EncoderHorizontal/lib/libEncoderHorizontal.a:
	@echo
	@echo "Building $@"
	@make -C EncoderHorizontal --no-print-directory

lib/libEncoderHorizontal.a: EncoderHorizontal/lib/libEncoderHorizontal.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libEncoderHorizontal.a gets properly rebuild
EncoderHorizontal/lib/libEncoderHorizontal.a: EncoderHorizontal/src/EncoderHorizontal.cpp EncoderHorizontal/include/EncoderHorizontal/EncoderHorizontal.h
EncoderHorizontal/lib/libEncoderHorizontal.a: EncoderHorizontal/src/encoder_cpp.cpp EncoderHorizontal/include/EncoderHorizontal/encoder_cpp.h

# protected region additional dependencies on begin

# protected region additional dependencies end