/**
 * Source file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { 

MainModel::MainModel() :
    Recursion<CSProcess>()
{
  SETNAME(this, "MainModel");

  // Initialize hardware channels
  LUNA::Clock::period_t mytimerExamplept_time_to_pt__periodic_timeChannelTimerPeriod;
  mytimerExamplept_time_to_pt__periodic_timeChannelTimerPeriod.seconds = 0;
  mytimerExamplept_time_to_pt__periodic_timeChannelTimerPeriod.nanoseconds = 250000000;
  mytimerExamplept_time_to_pt__periodic_timeChannel = new PeriodicTimerChannel(mytimerExamplept_time_to_pt__periodic_timeChannelTimerPeriod, false);

  // Initialize model objects
  mytimerExample = new example::example(mytimerExamplept_time_to_pt__periodic_timeChannel);
  SETNAME(mytimerExample, "timerExample");

  // Create Parallel group containing all architecture components
  parallelGroup = new Parallel(
    (CSPConstruct *) mytimerExample,
    NULL
  );
  SETNAME(parallelGroup, "parallelGroup");

  // Register group as top-level recursive object
  setToActivate(parallelGroup);
  setEvaluateCondition(true);
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // Destroy model objects
  delete mytimerExample;

  // Destroy channels
  delete mytimerExamplept_time_to_pt__periodic_timeChannel;
}

// Close namespace(s)
} 
