/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxinteg.h
 *  model: JIWY-co-sim
 *  expmt: JIWY-co-sim
 *  date:  May 31, 2019
 *  time:  7:02:36 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   * Vode Adams
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef XX_INTEG_H
#define XX_INTEG_H

/* 20-sim include files */
#include "xxtypes.h"
#include "xxmodel.h" /* For the xx_ModelInstance typedef */

/* the integration methods */
XXBoolean XXDiscreteInitialize (xx_ModelInstance* model_instance);
XXBoolean XXDiscreteTerminate (xx_ModelInstance* model_instance);
XXBoolean XXDiscreteStep (xx_ModelInstance* model_instance, XXDouble outputTime);

#endif

