/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxsubmod.h
 *  subm:  ControllerPan
 *  model: JIWY-co-sim
 *  expmt: JIWY-co-sim
 *  date:  May 31, 2019
 *  time:  7:02:36 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_SUBMOD_H
#define XX_SUBMOD_H

/* Our own include files */
#include "xxmodel.h"



/* The submodel functions */
XXBoolean XXInitializeSubmodel (xx_ModelInstance* model_instance);
XXBoolean XXCalculateSubmodel (xx_ModelInstance* model_instance, XXDouble t, XXDouble outputTime);
XXBoolean XXTerminateSubmodel (xx_ModelInstance* model_instance, XXDouble t);

#endif

