/**
 * Header file for the joy_code model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
#define JS_EVENT_BUTTON 0x01 // button pressed/released
#define JS_EVENT_AXIS   0x02 // joystick moved
#define JS_EVENT_INIT   0x80 // initial state of device
// protected region additional headers end

using namespace LUNA::CSP;

namespace joystick { namespace joy_code { 

class joy_code : public CodeBlock
{

public:
  // Define constructor and destructor
  joy_code(double &x, double &y);
  virtual ~joy_code();

  void execute();

private:

  // Class variables
  double &x;
  double &y;

  // protected region additional class members or functions on begin
  int fd;
  int button_state;

  struct js_event {
          __u32 time;     /* event timestamp in milliseconds */
          __s16 value;    /* value */
          __u8 type;      /* event type */
          __u8 number;    /* axis/button number */
  };

  struct js_event event;
  unsigned char type;
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
