/**
 * Header file for the joystick model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "joy_code.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace joystick { 

class joystick : public Sequential
{

public:
  // Define constructor and destructor
  joystick(ChannelIn<double> *joystick_hor, ChannelIn<double> *joystick_ver);
  virtual ~joystick();

private:

  // Class variables
  double x;
  double y;

  // Model objects
  joy_code::joy_code *myjoy_code;
  Writer<double> *myx_writer;
  Writer<double> *myy_writer;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
