/**
 * Header file for the example model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer12.h"
#include "Producer12.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace example { 

class example : public Sequential
{

public:
  // Define constructor and destructor
  example(ChannelIn<LUNA::Clock::period_t> *pt_time);
  virtual ~example();

private:

  // Class variables
  LUNA::Clock::period_t timeDummy;

  // Channel definitions
  UnbufferedChannel<int, One2In, Out2One> *myProducer12producer_ch1_out_to_Consumer12consumer_ch1_inChannel;
  UnbufferedChannel<int, One2In, Out2One> *myProducer12producer_ch2_out_to_Consumer12consumer_ch2_inChannel;

  // Model objects
  Consumer12::Consumer12 *myConsumer12;
  Producer12::Producer12 *myProducer12;
  Writer<LUNA::Clock::period_t> *mywr1;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
