/**
 * Header file for the EncoderV model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "cpp_encoderV.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace EncoderV { 

class EncoderV : public Sequential
{

public:
  // Define constructor and destructor
  EncoderV(ChannelOut<int> *pt_encoderV_in, ChannelIn<double> *pt_encoderV_out);
  virtual ~EncoderV();

private:

  // Class variables
  int input;
  double output;

  // Model objects
  cpp_encoderV::cpp_encoderV *mycpp_encoderV;
  Reader<int> *myreader_encoderV;
  Writer<double> *mywriter_encoderV;



  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} 
