/**
 * Header file for the plant model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "plant_compute.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace plant { 

class plant : public Sequential
{

public:
  // Define constructor and destructor
  plant(ChannelOut<double> *PanIn, ChannelIn<double> *PanOut, ChannelOut<double> *TiltIn, ChannelIn<double> *TiltOut);
  virtual ~plant();

private:

  // Class variables
  double v_ControlPan;
  double v_ControlTilt;
  double v_Pan;
  double v_Tilt;

  // Model objects
  plant_compute::plant_compute *myplant_compute;
  Reader<double> *myreaderPan;
  Reader<double> *myreaderTilt;
  Writer<double> *mywriterPan;
  Writer<double> *mywriterTilt;

  // Model groups
  Parallel *myPARALLEL;
  Parallel *myPARALLELP;
  Parallel *myPARALLELT;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
