/**
 * Source file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { 

MainModel::MainModel() :
    Recursion<CSProcess>()
{
  SETNAME(this, "MainModel");
  OSScheduler::Instance()->setSchedulerPolicy(FIFO);

  // Initialize hardware channels
  myModelTimeroscillator_to_osc_outChannel = new LUNA::CSP::RaMstix::RaMstixDigitalAnalogChannel<int>(10, true, 0);

  LUNA::Clock::period_t myModelTimerpt_time_to_pt_timeChannelTimerPeriod;
  myModelTimerpt_time_to_pt_timeChannelTimerPeriod.seconds = 0;
  myModelTimerpt_time_to_pt_timeChannelTimerPeriod.nanoseconds = 10000000;
  myModelTimerpt_time_to_pt_timeChannel = new PeriodicTimerChannel(myModelTimerpt_time_to_pt_timeChannelTimerPeriod, false);

  // Initialize model objects
  myModelTimer = new ModelTimer::ModelTimer(myModelTimeroscillator_to_osc_outChannel, myModelTimerpt_time_to_pt_timeChannel);
  SETNAME(myModelTimer, "ModelTimer");

  // Create Parallel group containing all architecture components
  parallelGroup = new Parallel(
    (CSPConstruct *) myModelTimer,
    NULL
  );
  SETNAME(parallelGroup, "parallelGroup");

  // Register group as top-level recursive object
  setToActivate(parallelGroup);
  setEvaluateCondition(true);
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // Destroy model objects
  delete myModelTimer;

  // Destroy channels
  delete myModelTimeroscillator_to_osc_outChannel;
  delete myModelTimerpt_time_to_pt_timeChannel;
}

// Close namespace(s)
} 
