/**
 * Source file for the cpp_pwm_h model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "cpp_pwm_h.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace PWM { namespace cpp_pwm_h { 

cpp_pwm_h::cpp_pwm_h(double &inH, double &outH) :
    CodeBlock(), inH(inH), outH(outH){
  SETNAME(this, "cpp_pwm_h");

  // protected region constructor on begin

  // protected region constructor end
}

cpp_pwm_h::~cpp_pwm_h()
{
  // protected region destructor on begin

  // protected region destructor end
}

void cpp_pwm_h::execute()
{
  // protected region execute code on begin
		   this->outH = inH;
  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
