/**
 * Source file for the cpp_pwm_v model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "cpp_pwm_v.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace PWM { namespace cpp_pwm_v { 

cpp_pwm_v::cpp_pwm_v(double &inV, double &outV) :
    CodeBlock(), inV(inV), outV(outV){
  SETNAME(this, "cpp_pwm_v");

  // protected region constructor on begin

  // protected region constructor end
}

cpp_pwm_v::~cpp_pwm_v()
{
  // protected region destructor on begin

  // protected region destructor end
}

void cpp_pwm_v::execute()
{
  // protected region execute code on begin
	   this->outV = inV;
  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
