/**
 * Header file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Hardware Channels
#include "csp/channels/PeriodicTimerChannel.h"

// Models
#include "example/example.h"

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  PeriodicTimerChannel *mytimerExamplept_time_to_pt__periodic_timeChannel;

  // Model objects
  example::example *mytimerExample;

  // Model groups
  Parallel *parallelGroup;
};

// Close namespace(s)
} 
