/**
 * Source file for the Plant model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Plant.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Plant { 

Plant::Plant(ChannelOut<int> *IN, ChannelIn<int> *Y) :
    Sequential(NULL)
{
  SETNAME(this, "Plant");

  // Initialize model objects
  myC_READER = new Reader<int>(&C_IN, IN);
  SETNAME(myC_READER, "C_READER");
  myY_WRITER = new Writer<int>(&Y_OUT, Y);
  SETNAME(myY_WRITER, "Y_WRITER");


  // Register model objects
  this->append_child(myC_READER);
  this->append_child(myY_WRITER);

  // protected region constructor on begin
  // protected region constructor end
}

Plant::~Plant()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model objects
  delete myY_WRITER;
  delete myC_READER;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
