/**
 * Source file for the SeqCon model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "SeqCon.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace SeqCon { 

SeqCon::SeqCon(ChannelIn<int> *out) :
    Sequential(NULL)
{
  SETNAME(this, "SeqCon");

  // Initialize model objects
  myPULSE_WRITER = new Writer<int>(&VAR1, out);
  SETNAME(myPULSE_WRITER, "PULSE_WRITER");


  // Register model objects
  this->append_child(myPULSE_WRITER);

  // protected region constructor on begin
  // protected region constructor end
}

SeqCon::~SeqCon()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model objects
  delete myPULSE_WRITER;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
