/**
 * Source file for the CPP_first model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "LoopCon/CPP_first.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace LoopCon { namespace CPP_first { 

CPP_first::CPP_first(int &MV, int &OUT) :
    CodeBlock(), MV(MV), OUT(OUT){
  SETNAME(this, "CPP_first");

  // protected region constructor on begin
  // protected region constructor end
}

CPP_first::~CPP_first()
{
  // protected region destructor on begin
  // protected region destructor end
}

void CPP_first::execute()
{
  // protected region execute code on begin
	if (OUT == NULL)
	{
		printf("not started \n");
		MV = 0;
	}
	else
		printf("out %d \n",OUT);

  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
