/**
 * Header file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Hardware Channels
#include "csp/channels/PeriodicTimerChannel.h"
#include "ramstixio/RaMstixEncChannel.h"

// Models
#include "ModelEn/ModelEn.h"

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  LUNA::CSP::RaMstix::RaMstixEncChannel<int> *myencoder_pt_to_encoderpt_outChannel;
  PeriodicTimerChannel *myencoderpt_timer_to_timerChannel;

  // Model objects
  ModelEn::ModelEn *myencoder;

  // Model groups
  Parallel *parallelGroup;
};

// Close namespace(s)
} 
