/**
 * Source file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { 

MainModel::MainModel() :
    Recursion<CSProcess>()
{
  SETNAME(this, "MainModel");
  OSScheduler::Instance()->setSchedulerPolicy(FIFO);

  // Initialize hardware channels
  myencoder_pt_to_encoderpt_outChannel = new LUNA::CSP::RaMstix::RaMstixEncChannel<int>(3, -1, 1, false, 0);

  LUNA::Clock::period_t myencoderpt_timer_to_timerChannelTimerPeriod;
  myencoderpt_timer_to_timerChannelTimerPeriod.seconds = 0;
  myencoderpt_timer_to_timerChannelTimerPeriod.nanoseconds = 1000000;
  myencoderpt_timer_to_timerChannel = new PeriodicTimerChannel(myencoderpt_timer_to_timerChannelTimerPeriod, false);

  // Initialize model objects
  myencoder = new ModelEn::ModelEn(myencoder_pt_to_encoderpt_outChannel, myencoderpt_timer_to_timerChannel);
  SETNAME(myencoder, "encoder");

  // Create Parallel group containing all architecture components
  parallelGroup = new Parallel(
    (CSPConstruct *) myencoder,
    NULL
  );
  SETNAME(parallelGroup, "parallelGroup");

  // Register group as top-level recursive object
  setToActivate(parallelGroup);
  setEvaluateCondition(true);
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // Destroy model objects
  delete myencoder;

  // Destroy channels
  delete myencoder_pt_to_encoderpt_outChannel;
  delete myencoderpt_timer_to_timerChannel;
}

// Close namespace(s)
} 
