/**
 * Source file for the cpp_consumer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer/cpp_consumer.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace ModelTimer { namespace Consumer { namespace cpp_consumer { 

cpp_consumer::cpp_consumer(int &varC1, int &varC2) :
    CodeBlock(), varC1(varC1), varC2(varC2){
  SETNAME(this, "cpp_consumer");

  // protected region constructor on begin
  // protected region constructor end
}

cpp_consumer::~cpp_consumer()
{
  // protected region destructor on begin
  // protected region destructor end
}

void cpp_consumer::execute()
{
  // protected region execute code on begin
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
