/**
 * Header file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Hardware Channels
#include "ramstixio/RaMstixPWMChannel.h"
#include "csp/channels/PeriodicTimerChannel.h"

// Models
#include "Model32/Model32.h"

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  LUNA::CSP::RaMstix::RaMstixPWMChannel<double> *myPWMpt_out_to_pwm_portChannel;
  PeriodicTimerChannel *myPWMpt_timer_to_timerChannel;

  // Model objects
  Model32::Model32 *myPWM;

  // Model groups
  Parallel *parallelGroup;
};

// Close namespace(s)
} 
