/**
 * Source file for the cpp_wr model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "cpp_wr.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace ModelTimer { namespace cpp_wr { 

cpp_wr::cpp_wr(bool &signal, LUNA::Clock::period_t &timeDummy) :
    CodeBlock(), signal(signal), timeDummy(timeDummy){
  SETNAME(this, "cpp_wr");

  // protected region constructor on begin
  // protected region constructor end
}

cpp_wr::~cpp_wr()
{
  // protected region destructor on begin
  // protected region destructor end
}

void cpp_wr::execute()
{
  // protected region execute code on begin
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
