/**
 * Source file for the CPP_pr model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer12/CPP_pr.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end
#include <sys/time.h>

namespace example { namespace Producer12 { namespace CPP_pr { 

CPP_pr::CPP_pr(int &var1, int &var2) :
    CodeBlock(), var1(var1), var2(var2){
  SETNAME(this, "CPP_pr");

  // protected region constructor on begin
  // protected region constructor end
}

CPP_pr::~CPP_pr()
{
  // protected region destructor on begin
  // protected region destructor end
}

void CPP_pr::execute()
{
  // protected region execute code on begin
static struct timespec time1;
 struct timespec time2;
 double accum;
 //gettimeofday(&currentTime,NULL);

if ( clock_gettime(CLOCK_REALTIME,&time2)== -1)
 perror("Error");
else
{
 accum = (double) (time2.tv_nsec-time1.tv_nsec)/1000000000L;
 if (accum > 0)
   printf("interval : %f \n",accum);
 time1=time2;
}


}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
