/**
 * Source file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { 

MainModel::MainModel() :
    Recursion<CSProcess>()
{
  SETNAME(this, "MainModel");
  OSScheduler::Instance()->setSchedulerPolicy(FIFO);

  // Initialize hardware channels
  myPWMpt_out_to_pwm_portChannel = new LUNA::CSP::RaMstix::RaMstixPWMChannel<double>(3, 2, 0, false, 21000, 0);

  LUNA::Clock::period_t myPWMpt_timer_to_timerChannelTimerPeriod;
  myPWMpt_timer_to_timerChannelTimerPeriod.seconds = 0;
  myPWMpt_timer_to_timerChannelTimerPeriod.nanoseconds = 0;
  myPWMpt_timer_to_timerChannel = new PeriodicTimerChannel(myPWMpt_timer_to_timerChannelTimerPeriod, false);

  // Initialize model objects
  myPWM = new Model32::Model32(myPWMpt_out_to_pwm_portChannel, myPWMpt_timer_to_timerChannel);
  SETNAME(myPWM, "PWM");

  // Create Parallel group containing all architecture components
  parallelGroup = new Parallel(
    (CSPConstruct *) myPWM,
    NULL
  );
  SETNAME(parallelGroup, "parallelGroup");

  // Register group as top-level recursive object
  setToActivate(parallelGroup);
  setEvaluateCondition(true);
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // Destroy model objects
  delete myPWM;

  // Destroy channels
  delete myPWMpt_out_to_pwm_portChannel;
  delete myPWMpt_timer_to_timerChannel;
}

// Close namespace(s)
} 
