/**
 * Header file for the Producer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Producer12/CPP_pr.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer12 { 

class Producer12 : public Sequential
{

public:
  // Define constructor and destructor
  Producer12(ChannelIn<int> *producer_ch1_out, ChannelIn<int> *producer_ch2_out);
  virtual ~Producer12();

private:

  // Class variables
  int var1;
  int var2;

  // Model objects
  CPP_pr::CPP_pr *myCPP_pr;
  Writer<int> *myproducer_writer_ch1;
  Writer<int> *myproducer_writer_ch2;

  // Model groups
  Sequential *mySEQUENTIAL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
