/**
 * Header file for the LoopCon model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "LoopCon/CPP_first.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace LoopCon { 

class LoopCon : public Sequential
{

public:
  // Define constructor and destructor
  LoopCon(ChannelIn<int> *COUT, ChannelOut<int> *MV, ChannelOut<int> *SP);
  virtual ~LoopCon();

private:

  // Class variables
  int V_MV;
  int V_OUT;
  int V_SP;

  // Model objects
  CPP_first::CPP_first *myCPP_first;
  Writer<int> *myOUT_WRITER;
  Reader<int> *myREADER_MV;
  Reader<int> *mySP_READER;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
