/**
 * Header file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "LoopCon.h"
#include "Plant.h"
#include "SeqCon.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  UnbufferedChannel<int, One2In, Out2One> *myLoopConCOUT_to_PlantINChannel;
  UnbufferedChannel<int, One2In, Out2One> *myPlantY_to_LoopConMVChannel;
  UnbufferedChannel<int, One2In, Out2One> *mySeqConout_to_LoopConSPChannel;

  // Model objects
  LoopCon::LoopCon *myLoopCon;
  Plant::Plant *myPlant;
  SeqCon::SeqCon *mySeqCon;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
