/**
 * Source file for the Step model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Step.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace Step { 

Step::Step(ChannelIn<double> *output, ChannelIn<double> *pulse_out) :
    Sequential(NULL)
{
  SETNAME(this, "Step");

  // Initialize model objects
  myXXStepModel = new XXStepModel::XXStepModel(v_output);
  SETNAME(myXXStepModel, "XXStepModel");
  mypulse_to_display = new Writer<double>(&v_output, pulse_out);
  SETNAME(mypulse_to_display, "pulse_to_display");
  myw_output = new Writer<double>(&v_output, output);
  SETNAME(myw_output, "w_output");

  // Create PRI_PARALLEL group
  myPRI_PARALLEL = new PriParallel(
    (CSPConstruct *) mypulse_to_display,
    (CSPConstruct *) myw_output,
    NULL
  );
  SETNAME(myPRI_PARALLEL, "PRI_PARALLEL");


  // Register model objects
  this->append_child(myXXStepModel);
  this->append_child(myPRI_PARALLEL);

  // protected region constructor on begin
  // protected region constructor end
}

Step::~Step()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myPRI_PARALLEL;

  // Destroy model objects
  delete myw_output;
  delete mypulse_to_display;
  delete myXXStepModel;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
