/**
 * Header file for the JoyStick model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "FMI_JoyStick.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace JoyStick { 

class JoyStick : public Sequential
{

public:
  // Define constructor and destructor
  JoyStick(ChannelIn<double> *JoyStickPan, ChannelIn<double> *JoyStickTilt);
  virtual ~JoyStick();

private:

  // Class variables
  double v_JoyStickPan;
  double v_JoyStickTilt;

  // Model objects
  FMI_JoyStick::FMI_JoyStick *myFMI_JoyStick;
  Writer<double> *myw_JoyStickPan;
  Writer<double> *myw_JoyStickTilt;

  // Model groups
  Parallel *myIO;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
