/**
 * Source file for the LinearSystem model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "LinearSystem.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace LinearSystem { 

LinearSystem::LinearSystem(ChannelIn<double> *time_to_display, ChannelOut<double> *u, ChannelIn<double> *y, ChannelIn<double> *y_out) :
    Sequential(NULL)
{
  SETNAME(this, "LinearSystem");

  // Initialize model objects
  myXXLinearSystemModel = new XXLinearSystemModel::XXLinearSystemModel(time, v_u, v_y);
  SETNAME(myXXLinearSystemModel, "XXLinearSystemModel");
  myY_to_display = new Writer<double>(&v_y, y_out);
  SETNAME(myY_to_display, "Y_to_display");
  myr_u = new Reader<double>(&v_u, u);
  SETNAME(myr_u, "r_u");
  myw_y = new Writer<double>(&v_y, y);
  SETNAME(myw_y, "w_y");
  mywriter_time = new Writer<double>(&time, time_to_display);
  SETNAME(mywriter_time, "writer_time");

  // Create PRI_PARALLEL group
  myPRI_PARALLEL = new PriParallel(
    (CSPConstruct *) myY_to_display,
    (CSPConstruct *) myw_y,
    (CSPConstruct *) mywriter_time,
    NULL
  );
  SETNAME(myPRI_PARALLEL, "PRI_PARALLEL");


  // Register model objects
  this->append_child(myXXLinearSystemModel);
  this->append_child(myPRI_PARALLEL);
  this->append_child(myr_u);

  // protected region constructor on begin
  // protected region constructor end
}

LinearSystem::~LinearSystem()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myPRI_PARALLEL;

  // Destroy model objects
  delete mywriter_time;
  delete myw_y;
  delete myr_u;
  delete myY_to_display;
  delete myXXLinearSystemModel;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
