# build.mk file for joystick.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libjoystick.a

joystick/lib/libjoystick.a:
	@echo
	@echo "Building $@"
	@make -C joystick --no-print-directory

lib/libjoystick.a: joystick/lib/libjoystick.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libjoystick.a gets properly rebuild
joystick/lib/libjoystick.a: joystick/src/joystick.cpp joystick/include/joystick/joystick.h
joystick/lib/libjoystick.a: joystick/src/joy_code.cpp joystick/include/joystick/joy_code.h

# protected region additional dependencies on begin
# protected region additional dependencies end