/**
 * Source file for the Model32 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Model32.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace Model32 { 

Model32::Model32(ChannelIn<double> *pt_out, ChannelIn<LUNA::Clock::period_t> *pt_timer) :
    Sequential(NULL)
{
  SETNAME(this, "Model32");

  // Initialize model objects
  mycpp_produce = new cpp_produce::cpp_produce(output);
  SETNAME(mycpp_produce, "cpp_produce");
  mywrOut = new Writer<double>(&output, pt_out);
  SETNAME(mywrOut, "wrOut");
  mywriter_time = new Writer<LUNA::Clock::period_t>(&timeDummy, pt_timer);
  SETNAME(mywriter_time, "writer_time");

  // Create SEQUENTIAL group
  mySEQUENTIAL = new Sequential(
    (CSPConstruct *) mycpp_produce,
    (CSPConstruct *) mywrOut,
    NULL
  );
  SETNAME(mySEQUENTIAL, "SEQUENTIAL");


  // Register model objects
  this->append_child(mywriter_time);
  this->append_child(mySEQUENTIAL);

  // protected region constructor on begin
  // protected region constructor end
}

Model32::~Model32()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete mySEQUENTIAL;

  // Destroy model objects
  delete mywriter_time;
  delete mywrOut;
  delete mycpp_produce;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
