/**
 * Header file for the CPP_cons21 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Consumer12 { namespace CPP_cons21 { 

class CPP_cons21 : public CodeBlock
{

public:
  // Define constructor and destructor
  CPP_cons21(int &varC1, int &varC2);
  virtual ~CPP_cons21();

  void execute();

private:

  // Class variables
  int &varC1;
  int &varC2;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
