/**
 * Header file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Hardware Channels
#include "ramstixio/RaMstixDigitalAnalogChannel.h"
#include "csp/channels/PeriodicTimerChannel.h"

// Models
#include "ModelTimer/ModelTimer.h"

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  LUNA::CSP::RaMstix::RaMstixDigitalAnalogChannel<int> *myModelTimeroscillator_to_osc_outChannel;
  PeriodicTimerChannel *myModelTimerpt_time_to_pt_timeChannel;

  // Model objects
  ModelTimer::ModelTimer *myModelTimer;

  // Model groups
  Parallel *parallelGroup;
};

// Close namespace(s)
} 
