/**
 * Header file for the cpp_show model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace display { namespace cpp_show { 

class cpp_show : public CodeBlock
{

public:
  // Define constructor and destructor
  cpp_show(double &varcon, double &varout, double &varpulse, double &vartime);
  virtual ~cpp_show();

  void execute();

private:

  // Class variables
  double &varcon;
  double &varout;
  double &varpulse;
  double &vartime;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
