# build.mk file for interleaving.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin

# protected region document description end

TARGETS+=bin/interleaving

interleaving/interleaving:
	@echo
	@echo "Building $@"
	@make -C interleaving --no-print-directory

bin/interleaving: interleaving/interleaving | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/interleaving gets properly rebuild
interleaving/interleaving: interleaving/src/main.cpp
interleaving/interleaving: interleaving/src/MainModel.cpp interleaving/include/MainModel.h
interleaving/interleaving: interleaving/src/A.cpp interleaving/include/A.h
interleaving/interleaving: interleaving/src/B.cpp interleaving/include/B.h
interleaving/interleaving: interleaving/src/C.cpp interleaving/include/C.h
interleaving/interleaving: interleaving/src/D.cpp interleaving/include/D.h

# protected region additional dependencies on begin

# protected region additional dependencies end