/**
 * Source file for the JIWY model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "JIWY.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace JIWY { 

JIWY::JIWY(ChannelOut<double> *encoder_h_out, ChannelOut<double> *encoder_v_out, ChannelOut<double> *joystick_h_in, ChannelOut<double> *joystick_v_in, ChannelIn<LUNA::Clock::period_t> *pt_timer, ChannelIn<double> *pwm_horizontal_in, ChannelIn<double> *pwm_vertical_in) :
    Sequential(NULL)
{
  SETNAME(this, "JIWY");

  // Initialize channels
  myHorizontalsteerIO_to_Checkhorizontal_outChannel = new UnbufferedChannel<double, One2In, Out2One>();
  myVerticalsteerIO_to_Checkvertical_outChannel = new UnbufferedChannel<double, One2In, Out2One>();

  // Initialize model objects
  myCheck = new Check::Check(myHorizontalsteerIO_to_Checkhorizontal_outChannel, pwm_horizontal_in, pwm_vertical_in, myVerticalsteerIO_to_Checkvertical_outChannel);
  SETNAME(myCheck, "Check");
  myHorizontal = new ControllerPan::ControllerPan(joystick_h_in, encoder_h_out, myHorizontalsteerIO_to_Checkhorizontal_outChannel);
  SETNAME(myHorizontal, "Horizontal");
  myVertical = new ControllerTilt::ControllerTilt(joystick_v_in, encoder_v_out, myVerticalsteerIO_to_Checkvertical_outChannel);
  SETNAME(myVertical, "Vertical");
  mytimer = new Writer<LUNA::Clock::period_t>(&timeDummy, pt_timer);
  SETNAME(mytimer, "timer");

  // Create PARALLEL group
  myPARALLEL = new Parallel(
    (CSPConstruct *) myHorizontal,
    (CSPConstruct *) myCheck,
    (CSPConstruct *) myVertical,
    NULL
  );
  SETNAME(myPARALLEL, "PARALLEL");


  // Register model objects
  this->append_child(myPARALLEL);
  this->append_child(mytimer);

  // protected region constructor on begin
  // protected region constructor end
}

JIWY::~JIWY()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myPARALLEL;

  // Destroy model objects
  delete mytimer;
  delete myVertical;
  delete myHorizontal;
  delete myCheck;

  // Destroy channels
  delete myHorizontalsteerIO_to_Checkhorizontal_outChannel;
  delete myVerticalsteerIO_to_Checkvertical_outChannel;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
