/**
 * Header file for the encoder_cpp model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace EncoderHorizontal { namespace encoder_cpp { 

class encoder_cpp : public CodeBlock
{

public:
  // Define constructor and destructor
  encoder_cpp(int &input, double &output);
  virtual ~encoder_cpp();

  void execute();

private:

  // Class variables
  int &input;
  double &output;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
