# build.mk file for ControllerPan.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin

# protected region document description end

TARGETS+=lib/libControllerPan.a

ControllerPan/lib/libControllerPan.a:
	@echo
	@echo "Building $@"
	@make -C ControllerPan --no-print-directory

lib/libControllerPan.a: ControllerPan/lib/libControllerPan.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libControllerPan.a gets properly rebuild
ControllerPan/lib/libControllerPan.a: ControllerPan/src/ControllerPan.cpp ControllerPan/include/ControllerPan/ControllerPan.h
ControllerPan/lib/libControllerPan.a: ControllerPan/src/XXControllerPanModel.cpp ControllerPan/include/ControllerPan/XXControllerPanModel.h ControllerPan/include/ControllerPan/xxsim/ControllerPanModel.hpp

# protected region additional dependencies on begin

# protected region additional dependencies end