/**
 * Header file for the Consumer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer/cpp_consumer.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace ModelTimer { namespace Consumer { 

class Consumer : public Sequential
{

public:
  // Define constructor and destructor
  Consumer(ChannelOut<int> *cons_in_ch1, ChannelOut<int> *cons_in_ch2);
  virtual ~Consumer();

private:

  // Class variables
  int varC1;
  int varC2;

  // Model objects
  cpp_consumer::cpp_consumer *mycpp_consumer;
  Reader<int> *myreader_cons_ch1;
  Reader<int> *myreader_cons_ch2;

  // Model groups
  Sequential *mySEQUENTIAL1;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
