/**
 * Header file for the cpp_wr model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace ModelTimer { namespace cpp_wr { 

class cpp_wr : public CodeBlock
{

public:
  // Define constructor and destructor
  cpp_wr(bool &signal, LUNA::Clock::period_t &timeDummy);
  virtual ~cpp_wr();

  void execute();

private:

  // Class variables
  bool &signal;
  LUNA::Clock::period_t &timeDummy;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
