/**
 * Header file for the ModelTimer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer.h"
#include "Producer.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace ModelTimer { 

class ModelTimer : public Sequential
{

public:
  // Define constructor and destructor
  ModelTimer(ChannelIn<int> *oscillator, ChannelIn<LUNA::Clock::period_t> *pt_time);
  virtual ~ModelTimer();

private:

  // Class variables
  LUNA::Clock::period_t timeDummy;

  // Channel definitions
  UnbufferedChannel<int, One2In, Out2One> *myProducerpro_out_ch2_to_Consumercons_in_ch2Channel;
  UnbufferedChannel<int, One2In, Out2One> *myProducerprod_out_ch1_to_Consumercons_in_ch1Channel;

  // Model objects
  Consumer::Consumer *myConsumer;
  Producer::Producer *myProducer;
  Writer<LUNA::Clock::period_t> *mytime_wr;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
