/**
 * Header file for the Producer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Producer/cpp_producer.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace ModelTimer { namespace Producer { 

class Producer : public Sequential
{

public:
  // Define constructor and destructor
  Producer(ChannelIn<int> *osci_port, ChannelIn<int> *pro_out_ch2, ChannelIn<int> *prod_out_ch1);
  virtual ~Producer();

private:

  // Class variables
  int oscSignal;
  int var1;
  int var2;

  // Model objects
  cpp_producer::cpp_producer *mycpp_producer;
  Writer<int> *mysignalWriter;
  Writer<int> *mywriter_ch1;
  Writer<int> *mywriter_ch2;

  // Model groups
  Sequential *mySEQUENTIAL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
