/**
 * Source file for the CPP_check model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer/CPP_check.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Producer { namespace CPP_check { 

CPP_check::CPP_check(int &var) :
    CodeBlock(), var(var){
  SETNAME(this, "CPP_check");

  // protected region constructor on begin

  // protected region constructor end
}

CPP_check::~CPP_check()
{
  // protected region destructor on begin

  // protected region destructor end
}

void CPP_check::execute()
{
  // protected region execute code on begin
 if (var >=10 && var <20)
 {
	 printf("---value %d doesn't pass the guards--- \n",var);
	 printf("---value %d will be forced to 0--- \n",var);
	 var=0;
 }
  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } } 
