/**
 * Source file for the CPP_pro12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer12/CPP_pro12.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Producer12 { namespace CPP_pro12 { 

CPP_pro12::CPP_pro12(int &var1, int &var2) :
    CodeBlock(), var1(var1), var2(var2){
  SETNAME(this, "CPP_pro12");

  // protected region constructor on begin

  // protected region constructor end
}

CPP_pro12::~CPP_pro12()
{
  // protected region destructor on begin

  // protected region destructor end
}

void CPP_pro12::execute()
{
  // protected region execute code on begin
	 var1 = rand() % 100;
	  var2 = rand() % 100;
	  printf("Producer channel 1  ProdVar1: %d \n",var1);
	  printf("Producer channel 2  ProdVar2: %d \n",var2);
  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } } 
