# build.mk file for ModelEn.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libModelEn.a

ModelEn/lib/libModelEn.a:
	@echo
	@echo "Building $@"
	@make -C ModelEn --no-print-directory

lib/libModelEn.a: ModelEn/lib/libModelEn.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libModelEn.a gets properly rebuild
ModelEn/lib/libModelEn.a: ModelEn/src/ModelEn.cpp ModelEn/include/ModelEn/ModelEn.h
ModelEn/lib/libModelEn.a: ModelEn/src/cpp_encoder.cpp ModelEn/include/ModelEn/cpp_encoder.h

# protected region additional dependencies on begin
# protected region additional dependencies end