# build.mk file for ModelTimer.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libModelTimer.a

ModelTimer/lib/libModelTimer.a:
	@echo
	@echo "Building $@"
	@make -C ModelTimer --no-print-directory

lib/libModelTimer.a: ModelTimer/lib/libModelTimer.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libModelTimer.a gets properly rebuild
ModelTimer/lib/libModelTimer.a: ModelTimer/src/ModelTimer.cpp ModelTimer/include/ModelTimer/ModelTimer.h
ModelTimer/lib/libModelTimer.a: ModelTimer/src/Producer.cpp ModelTimer/include/ModelTimer/Producer.h
ModelTimer/lib/libModelTimer.a: ModelTimer/src/Producer/cpp_producer.cpp ModelTimer/include/ModelTimer/Producer/cpp_producer.h
ModelTimer/lib/libModelTimer.a: ModelTimer/src/Consumer.cpp ModelTimer/include/ModelTimer/Consumer.h
ModelTimer/lib/libModelTimer.a: ModelTimer/src/Consumer/cpp_consumer.cpp ModelTimer/include/ModelTimer/Consumer/cpp_consumer.h

# protected region additional dependencies on begin
# protected region additional dependencies end