# build.mk file for model1.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/model1

model1/model1:
	@echo
	@echo "Building $@"
	@make -C model1 --no-print-directory

bin/model1: model1/model1 | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/model1 gets properly rebuild
model1/model1: model1/src/main.cpp
model1/model1: model1/src/MainModel.cpp model1/include/MainModel.h
model1/model1: model1/src/SeqCon.cpp model1/include/SeqCon.h
model1/model1: model1/src/LoopCon.cpp model1/include/LoopCon.h
model1/model1: model1/src/LoopCon/CPP_first.cpp model1/include/LoopCon/CPP_first.h
model1/model1: model1/src/Plant.cpp model1/include/Plant.h

# protected region additional dependencies on begin
# protected region additional dependencies end