/**
 * Header file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "ControllerPan/ControllerPan.h"
#include "ControllerTilt/ControllerTilt.h"
#include "JoyStick/JoyStick.h"
#include "plant/plant.h"

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  UnbufferedChannel<double, One2In, Out2One> *myControllerPansteerIO_to_plantPanInChannel;
  UnbufferedChannel<double, One2In, Out2One> *myControllerTiltsteerIO_to_plantTiltInChannel;
  UnbufferedChannel<double, One2In, Out2One> *myjoystickJoyStickPan_to_ControllerPanSetPointPanChannel;
  UnbufferedChannel<double, One2In, Out2One> *myjoystickJoyStickTilt_to_ControllerTiltSetPointTiltChannel;
  UnbufferedChannel<double, One2In, Out2One> *myplantPanOut_to_ControllerPanmeasIOChannel;
  UnbufferedChannel<double, One2In, Out2One> *myplantTiltOut_to_ControllerTiltmeasIOChannel;

  // Model objects
  ControllerPan::ControllerPan *myControllerPan;
  ControllerTilt::ControllerTilt *myControllerTilt;
  JoyStick::JoyStick *myjoystick;
  plant::plant *myplant;

  // Model groups
  Parallel *parallelGroup;
};

// Close namespace(s)
} 
