# build.mk file for Model2.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/Model2

Model2/Model2:
	@echo
	@echo "Building $@"
	@make -C Model2 --no-print-directory

bin/Model2: Model2/Model2 | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/Model2 gets properly rebuild
Model2/Model2: Model2/src/main.cpp
Model2/Model2: Model2/src/MainModel.cpp Model2/include/MainModel.h
Model2/Model2: Model2/src/Producer12.cpp Model2/include/Producer12.h
Model2/Model2: Model2/src/Producer12/CPP_pro12.cpp Model2/include/Producer12/CPP_pro12.h
Model2/Model2: Model2/src/Consumer12.cpp Model2/include/Consumer12.h
Model2/Model2: Model2/src/Consumer12/CPP_cons21.cpp Model2/include/Consumer12/CPP_cons21.h

# protected region additional dependencies on begin
# protected region additional dependencies end