/**
 * Source file for the XXControllerPanModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * 20-sim C++ glue code to connect to ControllerPanModel
 * Modifying this file is absolutely not recommended!
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "XXControllerPanModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace ControllerPan { namespace XXControllerPanModel { 

XXControllerPanModel::XXControllerPanModel(double &SetPointPan, double &measIO, double &steerIO) :
    CodeBlock(), SetPointPan(SetPointPan), measIO(measIO), steerIO(steerIO){
  SETNAME(this, "XXControllerPanModel");

  using namespace LUNA::xxsim;

  m_model = new ControllerPanModel;


  m_model->addOutput(&steerIO, XXVARIABLE, 6, 1, 1);


  m_model->addInput(&measIO, XXVARIABLE, 7, 1, 1);


  m_model->addInput(&SetPointPan, XXVARIABLE, 8, 1, 1);


  m_model->start();
}

XXControllerPanModel::~XXControllerPanModel()
{
    m_model->stop();

	//@todo Clean up adapters

    delete m_model;
}

void XXControllerPanModel::execute()
{
    m_model->step();
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
