/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxmodel.c
 *  model: JIWY-co-sim
 *  expmt: JIWY-co-sim
 *  date:  May 31, 2019
 *  time:  7:02:08 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   XXDouble xx_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXString xx_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void XXCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxfuncs.h"


#if (6 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
/* this method is called before calculation is possible */
void XXModelInitialize (xx_ModelInstance* model_instance)
{
	/* set the parameters */
	xx_P[0] = 1.0;		/* PulsePan\start_time {s} */
	xx_P[1] = 5.0;		/* PulsePan\stop_time {s} */
	xx_P[2] = 1.0;		/* PulsePan\amplitude {} */
	xx_P[3] = 2.0;		/* PulseTilt\start_time {s} */
	xx_P[4] = 6.0;		/* PulseTilt\stop_time {s} */
	xx_P[5] = -1.0;		/* PulseTilt\amplitude {} */


}
#if (6 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void XXCalculateInitial (xx_ModelInstance* model_instance)
{


}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void XXCalculateStatic (xx_ModelInstance* model_instance)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void XXCalculateInput (xx_ModelInstance* model_instance)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void XXCalculateDynamic (xx_ModelInstance* model_instance)
{
	/* PulsePan\change = timeevent (PulsePan\start_time) or timeevent (PulsePan\stop_time); */
	xx_V[1] = XXTimeEvent (xx_P[0], 0) || XXTimeEvent (xx_P[1], 1);

	/* PulsePan\output = PulsePan\amplitude * (step (PulsePan\start_time) - step (PulsePan\stop_time)); */
	xx_V[0] = xx_P[2] * (XXStep (xx_P[0], xx_time) - XXStep (xx_P[1], xx_time));

	/* PulseTilt\change = timeevent (PulseTilt\start_time) or timeevent (PulseTilt\stop_time); */
	xx_V[3] = XXTimeEvent (xx_P[3], 2) || XXTimeEvent (xx_P[4], 3);

	/* PulseTilt\output = PulseTilt\amplitude * (step (PulseTilt\start_time) - step (PulseTilt\stop_time)); */
	xx_V[2] = xx_P[5] * (XXStep (xx_P[3], xx_time) - XXStep (xx_P[4], xx_time));

	/* JoyStickPan = PulsePan\output; */
	xx_V[4] = xx_V[0];

	/* JoyStickTilt = PulseTilt\output; */
	xx_V[5] = xx_V[2];


	/* increment the step counter */
	model_instance->steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void XXCalculateOutput (xx_ModelInstance* model_instance)
{

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void XXCalculateFinal (xx_ModelInstance* model_instance)
{

}

/* this method is called after all calculations are performed */
void XXModelTerminate(xx_ModelInstance* model_instance)
{
}

XXBoolean XXModelTimeEvent (xx_ModelInstance* model_instance, XXDouble argument, XXInteger id)
{
	if (model_instance->major)
	{
		XXDouble prevValue = model_instance->time_event[id];
		model_instance->time_event[id] = model_instance->time;
		if ((model_instance->time >= argument) && (prevValue < argument))
		{
			return XXTRUE;
		}
	}
	return XXFALSE;
}

