/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxmodel.h
 *  subm:  JoyStick
 *  model: JIWY-co-sim
 *  expmt: JIWY-co-sim
 *  date:  May 31, 2019
 *  time:  7:02:08 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_MODEL_H
#define XX_MODEL_H

/* Our own include files */
#include "xxtypes.h"
#include "fmi2Functions.h"

/* Model size constants */
#define xx_constants_count 0
#define xx_parameter_count 6
#define xx_parameter_index_start 0
#define xx_parameter_index_end (0 + 6 - 1)
#define xx_initialvalue_count 0
#define xx_variable_count 6
#define xx_state_count 0

#define xx_timeevent_count 4


typedef struct xx_ModelInstance
{
/* Global pointer to co-simulator callback functions */
	const fmi2CallbackFunctions* fmiCallbackFunctions;

	/* FMU */
	fmi2String instanceName;

	/* Store the path to the extracted resource folder location provided by the
	 * co-simulation engine for this model instance
	 */
	const char* resourceLocation;

	/* Simulation variables */
	XXDouble start_time;
	XXDouble finish_time;
	XXBoolean m_use_finish_time;
	XXDouble step_size;
	XXDouble time;
	XXInteger steps;
	XXBoolean initialize;
	XXBoolean major;
	XXBoolean stop_simulation;
	XXBoolean parameters_updated;

	/* Model state */
	XXDouble MEMORY[
		xx_parameter_count + 
		xx_variable_count + 
		1
	];

	/* discrete time can be behind of continuous time
	 * dependent on the step size 
	 */
	XXDouble m_discrete_time;
	/* Memory offset pointers */
	XXDouble* P;	/* parameters */
	XXDouble* V;		/* variables */
	XXDouble time_event[xx_timeevent_count];
} xx_ModelInstance;

/* Variable arrays */
#define xx_P model_instance->P
#define xx_V model_instance->V

#define xx_time model_instance->time
#define xx_step_size model_instance->step_size
#define xx_initialize model_instance->initialize
#define xx_major model_instance->major
#define xx_start_time model_instance->start_time
#define xx_finish_time model_instance->finish_time

/* Initialization methods */
void XXModelInitialize (xx_ModelInstance* model_instance);
void XXModelTerminate (xx_ModelInstance* model_instance);

/* Computation methods */
void XXCalculateInitial (xx_ModelInstance* model_instance);
void XXCalculateStatic (xx_ModelInstance* model_instance);
void XXCalculateInput (xx_ModelInstance* model_instance);
void XXCalculateDynamic (xx_ModelInstance* model_instance);
void XXCalculateOutput (xx_ModelInstance* model_instance);
void XXCalculateFinal (xx_ModelInstance* model_instance);

XXBoolean XXModelTimeEvent (xx_ModelInstance* model_instance, XXDouble argument, XXInteger id);
#define XXTimeEvent(argument, id) XXModelTimeEvent(model_instance, argument, id)
#endif

