/**
 * Header file for the display model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "display/cpp_show.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace display { 

class display : public Sequential
{

public:
  // Define constructor and destructor
  display(ChannelOut<double> *control, ChannelOut<double> *pulse, ChannelOut<double> *y_out);
  virtual ~display();

private:

  // Class variables
  double control_var;
  double pulse_var;
  double y_var;

  // Model objects
  cpp_show::cpp_show *mycpp_show;
  Reader<double> *myreader_control;
  Reader<double> *myreader_out;
  Reader<double> *myreader_pulse;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
