/**
 * Header file for the cpp_consumer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace ModelTimer { namespace Consumer { namespace cpp_consumer { 

class cpp_consumer : public CodeBlock
{

public:
  // Define constructor and destructor
  cpp_consumer(int &varC1, int &varC2);
  virtual ~cpp_consumer();

  void execute();

private:

  // Class variables
  int &varC1;
  int &varC2;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
