# build.mk file for EncoderV.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin

# protected region document description end

TARGETS+=lib/libEncoderV.a

EncoderV/lib/libEncoderV.a:
	@echo
	@echo "Building $@"
	@make -C EncoderV --no-print-directory

lib/libEncoderV.a: EncoderV/lib/libEncoderV.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libEncoderV.a gets properly rebuild
EncoderV/lib/libEncoderV.a: EncoderV/src/EncoderV.cpp EncoderV/include/EncoderV/EncoderV.h
EncoderV/lib/libEncoderV.a: EncoderV/src/cpp_encoderV.cpp EncoderV/include/EncoderV/cpp_encoderV.h

# protected region additional dependencies on begin

# protected region additional dependencies end