/**
 * Header file for the cpp_encoder model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace ModelEn { namespace cpp_encoder { 

class cpp_encoder : public CodeBlock
{

public:
  // Define constructor and destructor
  cpp_encoder(int &In_En);
  virtual ~cpp_encoder();

  void execute();

private:

  // Class variables
  int &In_En;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
