/**
 * Header file for the cpp_horizontal_check model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace JIWY { namespace Check { namespace cpp_horizontal_check { 

class cpp_horizontal_check : public CodeBlock
{

public:
  // Define constructor and destructor
  cpp_horizontal_check(double &horizontal);
  virtual ~cpp_horizontal_check();

  void execute();

private:

  // Class variables
  double &horizontal;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
