/**
 * Header file for the Check model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Check/cpp_horizontal_check.h"
#include "Check/cpp_vertical.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace JIWY { namespace Check { 

class Check : public Parallel
{

public:
  // Define constructor and destructor
  Check(ChannelOut<double> *horizontal_out, ChannelIn<double> *pwm_horizontal, ChannelIn<double> *pwm_vertical, ChannelOut<double> *vertical_out);
  virtual ~Check();

private:

  // Class variables
  double horizontal;
  double vertical;

  // Model objects
  cpp_horizontal_check::cpp_horizontal_check *mycpp_horizontal_check;
  cpp_vertical::cpp_vertical *mycpp_vertical;
  Reader<double> *myreader_check_horizontal;
  Reader<double> *myreader_check_vertical;
  Writer<double> *mywriter_check_horizontal;
  Writer<double> *mywriter_check_vertical;

  // Model groups
  Sequential *mySEQUENTIALH;
  Sequential *mySEQUENTIALV;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
