/**
 * Header file for the JIWY model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Check.h"
#include "ControllerPan/ControllerPan.h"
#include "ControllerTilt/ControllerTilt.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace JIWY { 

class JIWY : public Sequential
{

public:
  // Define constructor and destructor
  JIWY(ChannelOut<double> *encoder_h_out, ChannelOut<double> *encoder_v_out, ChannelOut<double> *joystick_h_in, ChannelOut<double> *joystick_v_in, ChannelIn<LUNA::Clock::period_t> *pt_timer, ChannelIn<double> *pwm_horizontal_in, ChannelIn<double> *pwm_vertical_in);
  virtual ~JIWY();

private:

  // Class variables
  LUNA::Clock::period_t timeDummy;

  // Channel definitions
  UnbufferedChannel<double, One2In, Out2One> *myHorizontalsteerIO_to_Checkhorizontal_outChannel;
  UnbufferedChannel<double, One2In, Out2One> *myVerticalsteerIO_to_Checkvertical_outChannel;

  // Model objects
  Check::Check *myCheck;
  ControllerPan::ControllerPan *myHorizontal;
  ControllerTilt::ControllerTilt *myVertical;
  Writer<LUNA::Clock::period_t> *mytimer;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
