# build.mk file for example.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libexample.a

example/lib/libexample.a:
	@echo
	@echo "Building $@"
	@make -C example --no-print-directory

lib/libexample.a: example/lib/libexample.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libexample.a gets properly rebuild
example/lib/libexample.a: example/src/example.cpp example/include/example/example.h
example/lib/libexample.a: example/src/Producer12.cpp example/include/example/Producer12.h
example/lib/libexample.a: example/src/Producer12/CPP_pr.cpp example/include/example/Producer12/CPP_pr.h
example/lib/libexample.a: example/src/Consumer12.cpp example/include/example/Consumer12.h
example/lib/libexample.a: example/src/Consumer12/CPP_cons.cpp example/include/example/Consumer12/CPP_cons.h

# protected region additional dependencies on begin
# protected region additional dependencies end