/**
 * Header file for the cpp_produce model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace Model32 { namespace cpp_produce { 

class cpp_produce : public CodeBlock
{

public:
  // Define constructor and destructor
  cpp_produce(double &outSignal);
  virtual ~cpp_produce();

  void execute();

private:

  // Class variables
  double &outSignal;

  // protected region additional class members or functions on begin
  int16_t deadzone_check(int16_t);
  double translation(int16_t);
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
