/**
 * Header file for the CPP_first model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace LoopCon { namespace CPP_first { 

class CPP_first : public CodeBlock
{

public:
  // Define constructor and destructor
  CPP_first(int &MV, int &OUT);
  virtual ~CPP_first();

  void execute();

private:

  // Class variables
  int &MV;
  int &OUT;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
