/**
 * Header file for the XXControllerPanModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * 20-sim C++ glue code to connect to ControllerPanModel
 * Modifying this file is absolutely not recommended!
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
#include "xxsim/ControllerPanModel.hpp" 
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace ControllerPan { namespace XXControllerPanModel { 

class XXControllerPanModel : public CodeBlock
{

public:
  // Define constructor and destructor
  XXControllerPanModel(double &SetPointPan, double &measIO, double &steerIO);
  virtual ~XXControllerPanModel();

  void execute();

private:

  // Class variables
  double &SetPointPan;
  double &measIO;
  double &steerIO;

  ControllerPanModel *m_model;
};

// Close namespace(s)
} } 
