/**
 * Source file for the CPP_cons model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer12/CPP_cons.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace example { namespace Consumer12 { namespace CPP_cons { 

CPP_cons::CPP_cons(int &varC1, int &varC2) :
    CodeBlock(), varC1(varC1), varC2(varC2){
  SETNAME(this, "CPP_cons");

  // protected region constructor on begin
  // protected region constructor end
}

CPP_cons::~CPP_cons()
{
  // protected region destructor on begin
  // protected region destructor end
}

void CPP_cons::execute()
{
  // protected region execute code on begin
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
