/**
 * Source file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { 

MainModel::MainModel() :
    Recursion<CSProcess>()
{
  SETNAME(this, "MainModel");

  // Initialize channels
  myLoopConoutput_to_PlantuChannel = new UnbufferedChannel<double, One2In, Out2One>();
  myPlanty_to_LoopConMVChannel = new UnbufferedChannel<double, One2In, Out2One>();
  mySeqConoutput_to_LoopConSPChannel = new UnbufferedChannel<double, One2In, Out2One>();

  // Initialize model objects
  myLoopCon = new Controller::Controller(myPlanty_to_LoopConMVChannel, mySeqConoutput_to_LoopConSPChannel, myLoopConoutput_to_PlantuChannel);
  SETNAME(myLoopCon, "LoopCon");
  myPlant = new LinearSystem::LinearSystem(myLoopConoutput_to_PlantuChannel, myPlanty_to_LoopConMVChannel);
  SETNAME(myPlant, "Plant");
  mySeqCon = new Step::Step(mySeqConoutput_to_LoopConSPChannel);
  SETNAME(mySeqCon, "SeqCon");

  // Create PARALLEL group
  myPARALLEL = new Parallel(
    (CSPConstruct *) myLoopCon,
    (CSPConstruct *) myPlant,
    (CSPConstruct *) mySeqCon,
    NULL
  );
  SETNAME(myPARALLEL, "PARALLEL");

  // Register PARALLEL as top-level recursive object
  setToActivate(myPARALLEL);
  setEvaluateCondition(true);


  // protected region constructor on begin
  // protected region constructor end
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myPARALLEL;

  // Destroy model objects
  delete mySeqCon;
  delete myPlant;
  delete myLoopCon;

  // Destroy channels
  delete myLoopConoutput_to_PlantuChannel;
  delete myPlanty_to_LoopConMVChannel;
  delete mySeqConoutput_to_LoopConSPChannel;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
