/**
 * Source file for the joy_code model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "joy_code.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace joystick { namespace joy_code {

joy_code::joy_code(double &x, double &y) :
    CodeBlock(), x(x), y(y){
  SETNAME(this, "joy_code");

  // protected region constructor on begin
  fd = open("/dev/input/js0", O_NONBLOCK);
  // protected region constructor end
}

joy_code::~joy_code()
{
  // protected region destructor on begin

  // protected region destructor end
}

void joy_code::execute()
{
  // protected region execute code on begin
	read(fd, &event, sizeof(event));
	  if(event.type == JS_EVENT_AXIS)
	  {
		  if(event.number == 0)
		  {
			  x = (double)event.value/16000; //TODO

			  //printf("Axis X: %f,\t Axis Y: %f\n", var_hor_joy, var_ver_joy);
		  }
		  else if(event.number == 1)
		  {
			  y = (double)event.value/16000; //TODO

			  //printf("Axis X: %f,\t Axis Y: %f\n", var_hor_joy, var_ver_joy);
		  }

	  }
	  else if(event.type == JS_EVENT_BUTTON)
	  {
		  if(event.number==3)
			  printf("Smile\n");
	  }
  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
