/**
 * Source file for the joystick model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "joystick.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace joystick { 

joystick::joystick(ChannelIn<double> *joystick_hor, ChannelIn<double> *joystick_ver) :
    Sequential(NULL)
{
  SETNAME(this, "joystick");

  // Initialize model objects
  myjoy_code = new joy_code::joy_code(x, y);
  SETNAME(myjoy_code, "joy_code");
  myx_writer = new Writer<double>(&x, joystick_hor);
  SETNAME(myx_writer, "x_writer");
  myy_writer = new Writer<double>(&y, joystick_ver);
  SETNAME(myy_writer, "y_writer");

  // Create PARALLEL group
  myPARALLEL = new Parallel(
    (CSPConstruct *) myx_writer,
    (CSPConstruct *) myy_writer,
    NULL
  );
  SETNAME(myPARALLEL, "PARALLEL");


  // Register model objects
  this->append_child(myjoy_code);
  this->append_child(myPARALLEL);

  // protected region constructor on begin
  // protected region constructor end
}

joystick::~joystick()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myPARALLEL;

  // Destroy model objects
  delete myy_writer;
  delete myx_writer;
  delete myjoy_code;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
