/**
 * Header file for the cpp_pwm_h model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace PWM { namespace cpp_pwm_h { 

class cpp_pwm_h : public CodeBlock
{

public:
  // Define constructor and destructor
  cpp_pwm_h(double &inH, double &outH);
  virtual ~cpp_pwm_h();

  void execute();

private:

  // Class variables
  double &inH;
  double &outH;

  // protected region additional class members or functions on begin
  double translation(int16_t);
  int16_t deadzone_check(int16_t);
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
