/**
 * Header file for the cpp_pwm_v model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace PWM { namespace cpp_pwm_v { 

class cpp_pwm_v : public CodeBlock
{

public:
  // Define constructor and destructor
  cpp_pwm_v(double &inV, double &outV);
  virtual ~cpp_pwm_v();

  void execute();

private:

  // Class variables
  double &inV;
  double &outV;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
