/**
 * Header file for the PWM model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "cpp_pwm_h.h"
#include "cpp_pwm_v.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace PWM { 

class PWM : public Parallel
{

public:
  // Define constructor and destructor
  PWM(ChannelOut<double> *pwm_in_horizontal, ChannelOut<double> *pwm_in_vertical, ChannelIn<double> *pwm_out_horizontal, ChannelIn<double> *pwm_out_vertical);
  virtual ~PWM();

private:

  // Class variables
  double inputH;
  double inputV;
  double outputH;
  double outputV;

  // Model objects
  cpp_pwm_h::cpp_pwm_h *mycpp_pwm_h;
  cpp_pwm_v::cpp_pwm_v *mycpp_pwm_v;
  Reader<double> *myreaderPWM_h;
  Reader<double> *myreader_pwm_vertical;
  Writer<double> *mywriterPWM_h;
  Writer<double> *mywriterPWM_v;

  // Model groups
  Sequential *mySEQUENTIALH;
  Sequential *mySEQUENTIALV;



  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} 
