# build.mk file for PWM.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin

# protected region document description end

TARGETS+=lib/libPWM.a

PWM/lib/libPWM.a:
	@echo
	@echo "Building $@"
	@make -C PWM --no-print-directory

lib/libPWM.a: PWM/lib/libPWM.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libPWM.a gets properly rebuild
PWM/lib/libPWM.a: PWM/src/PWM.cpp PWM/include/PWM/PWM.h
PWM/lib/libPWM.a: PWM/src/cpp_pwm_h.cpp PWM/include/PWM/cpp_pwm_h.h
PWM/lib/libPWM.a: PWM/src/cpp_pwm_v.cpp PWM/include/PWM/cpp_pwm_v.h

# protected region additional dependencies on begin

# protected region additional dependencies end