/**
 * Source file for the B model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "B.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace B { 

B::B() :
    CodeBlock()
{
  SETNAME(this, "B");

  // protected region constructor on begin

  // protected region constructor end
}

B::~B()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin

  // protected region destructor end
}

void B::execute()
{
  // protected region execute code on begin

  // protected region execute code end
}



// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
