/**
 * Source file for the D model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "D.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace D { 

D::D() :
    CodeBlock()
{
  SETNAME(this, "D");

  // protected region constructor on begin

  // protected region constructor end
}

D::~D()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin

  // protected region destructor end
}

void D::execute()
{
  // protected region execute code on begin

  // protected region execute code end
}



// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
