/**
 * Source file for the display model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "display.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace display { 

display::display(ChannelOut<double> *control, ChannelOut<double> *pulse, ChannelOut<double> *y_out) :
    Sequential(NULL)
{
  SETNAME(this, "display");

  // Initialize model objects
  mycpp_show = new cpp_show::cpp_show(control_var, y_var, pulse_var);
  SETNAME(mycpp_show, "cpp_show");
  myreader_control = new Reader<double>(&control_var, control);
  SETNAME(myreader_control, "reader_control");
  myreader_out = new Reader<double>(&y_var, y_out);
  SETNAME(myreader_out, "reader_out");
  myreader_pulse = new Reader<double>(&pulse_var, pulse);
  SETNAME(myreader_pulse, "reader_pulse");

  // Create PARALLEL group
  myPARALLEL = new Parallel(
    (CSPConstruct *) myreader_out,
    (CSPConstruct *) myreader_control,
    (CSPConstruct *) myreader_pulse,
    NULL
  );
  SETNAME(myPARALLEL, "PARALLEL");


  // Register model objects
  this->append_child(myPARALLEL);
  this->append_child(mycpp_show);

  // protected region constructor on begin
  // protected region constructor end
}

display::~display()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myPARALLEL;

  // Destroy model objects
  delete myreader_pulse;
  delete myreader_out;
  delete myreader_control;
  delete mycpp_show;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
