/**
 * Header file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Hardware Channels
#include "ramstixio/RaMstixEncChannel.h"
#include "ramstixio/RaMstixPWMChannel.h"
#include "csp/channels/PeriodicTimerChannel.h"

// Models
#include "EncoderHorizontal/EncoderHorizontal.h"
#include "EncoderV/EncoderV.h"
#include "JIWY/JIWY.h"
#include "joystick/joystick.h"
#include "PWM/PWM.h"

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  UnbufferedChannel<double, One2In, Out2One> *myEncoderHpt_encoderH_out_to_JIWYencoder_h_outChannel;
  UnbufferedChannel<double, One2In, Out2One> *myEncoderVpt_encoderV_out_to_JIWYencoder_v_outChannel;
  PeriodicTimerChannel *myJIWYpt_timer_to_timer_ptChannel;
  UnbufferedChannel<double, One2In, Out2One> *myJIWYpwm_horizontal_in_to_PWMpwm_in_horizontalChannel;
  UnbufferedChannel<double, One2In, Out2One> *myJIWYpwm_vertical_in_to_PWMpwm_in_verticalChannel;
  UnbufferedChannel<double, One2In, Out2One> *myJoystickjoystick_hor_to_JIWYjoystick_h_inChannel;
  UnbufferedChannel<double, One2In, Out2One> *myJoystickjoystick_ver_to_JIWYjoystick_v_inChannel;
  LUNA::CSP::RaMstix::RaMstixPWMChannel<double> *myPWMpwm_out_horizontal_to_pwm_robot_hChannel;
  LUNA::CSP::RaMstix::RaMstixPWMChannel<double> *myPWMpwm_out_vertical_to_pwm_robot_vChannel;
  LUNA::CSP::RaMstix::RaMstixEncChannel<int> *mypt_encoder_h_to_EncoderHencoder_ptChannel;
  LUNA::CSP::RaMstix::RaMstixEncChannel<int> *mypt_encoder_v_to_EncoderVpt_encoderV_inChannel;

  // Model objects
  EncoderHorizontal::EncoderHorizontal *myEncoderH;
  EncoderV::EncoderV *myEncoderV;
  JIWY::JIWY *myJIWY;
  joystick::joystick *myJoystick;
  PWM::PWM *myPWM;

  // Model groups
  Parallel *parallelGroup;
};

// Close namespace(s)
} 
