/**
 * Source file for the CPP_r3 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer/CPP_r3.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Consumer { namespace CPP_r3 { 

CPP_r3::CPP_r3(int &var3) :
    CodeBlock(), var3(var3){
  SETNAME(this, "CPP_r3");

  // protected region constructor on begin
  // protected region constructor end
}

CPP_r3::~CPP_r3()
{
  // protected region destructor on begin
  // protected region destructor end
}

void CPP_r3::execute()
{
  // protected region execute code on begin
	printf("Channel 3 received: %d \n",var3);
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
