/**
 * Source file for the CPP_r2 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer/CPP_r2.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Consumer { namespace CPP_r2 { 

CPP_r2::CPP_r2(int &var2) :
    CodeBlock(), var2(var2){
  SETNAME(this, "CPP_r2");

  // protected region constructor on begin
  // protected region constructor end
}

CPP_r2::~CPP_r2()
{
  // protected region destructor on begin
  // protected region destructor end
}

void CPP_r2::execute()
{
  // protected region execute code on begin
	printf("Channel 2 received: %d \n",var2);
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
